version: "3"

services:
  web:
    build: ./web
    ports: ["5100:5100"]
    container_name: sim_flask-api
    links: 
      - database
  database:
    build: ./database
    container_name: sim_mongodb
